
-- Create table ROLES 
CREATE TABLE ROLES(
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) UNIQUE NOT NULL,
    ROLE_DESCRIPTION TEXT
);

-- Create table ACTIVE_STATUS 
CREATE TABLE ACTIVE_STATUS(
    ACTIVE_STATUS_ID SERIAL PRIMARY KEY,
    ACTIVE_STATUS_NAME VARCHAR(50) UNIQUE NOT NULL,
    ACTIVE_STATUS_DESCRIPTION TEXT
);

-- Create table USERS
CREATE TABLE USERS(
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    HASHED_PASSWORD TEXT NOT NULL,
    ROLE_ID INT NOT NULL REFERENCES ROLES(ROLE_ID),
    ACTIVE_STATUS_ID INT NOT NULL REFERENCES ACTIVE_STATUS(ACTIVE_STATUS_ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP
);

-- Create table USER_PROFILES
CREATE TABLE USER_PROFILES (
    USER_ID INT PRIMARY KEY REFERENCES USERS(USER_ID),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);

-- Create table USER_SETTINGS
CREATE TABLE USER_SETTINGS (
    USER_ID INT PRIMARY KEY REFERENCES USERS(USER_ID),
    COLOR_THEME VARCHAR(20) DEFAULT 'light',
    TIMEZONE TEXT DEFAULT 'UTC'
);
