services:
  database:
    container_name: postgres-database
    image: postgres:17
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - flask_app_network
    restart: always
  backend:
    container_name: flask-backend
    build: 
      context: ./backend/docker/
    volumes:
      - ./application:/usr/local/flask_app/
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - flask_app_network
volumes:
  pgdata:
networks:
  flask_app_network:
    driver: bridge
