services:
  database:
    container_name: postgres-database
    image: postgres:17
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
